---
- name: install espanso
  ansible.builtin.homebrew_cask:
    name: espanso
    state: present

- name: Set fact icloud path
  set_fact:
    icloud: "{{ ansible_env.HOME }}/Library/Mobile Documents/com~apple~CloudDocs"
    icloud_path: "{{ ansible_env.HOME }}/Library/Mobile Documents/com~apple~CloudDocs/{{ path_inside_icloud }}"
    icloud_config_path: "{{ ansible_env.HOME }}/Library/Mobile Documents/com~apple~CloudDocs/{{ path_inside_icloud }}/config"
    icloud_match_path: "{{ ansible_env.HOME }}/Library/Mobile Documents/com~apple~CloudDocs/{{ path_inside_icloud }}/match"
    espanso_path: "{{ ansible_env.HOME }}/Library/Application Support/espanso"
  
- name: Does icloud path exists?
  ansible.builtin.stat:
    path: "{{ icloud }}"
  register: icloud_dir

- name: Does espanso icloud path exists?
  ansible.builtin.stat:
    path: "{{ icloud_path }}"
  register: icloud_path_dir

- name: Does espanso icloud config path exists?
  ansible.builtin.stat:
    path: "{{ icloud_config_path }}"
  register: icloud_config_path_dir

- name: Does espanso icloud match path exists?
  ansible.builtin.stat:
    path: "{{ icloud_match_path }}"
  register: icloud_match_path_dir

- name: Does espanso path exists?
  ansible.builtin.stat:
    path: "{{ espanso_path }}"
  register: espanso_dir

# Make the cloud directory
- name: Ensure icloud path exists
  ansible.builtin.file:
    path: "{{ icloud_path }}"
    state: directory
    mode: 0700

# Copy the existing espanso configuration to the cloud 
- name: Copy existing structure to icloud
  ansible.builtin.include_tasks: copy_structure.yml
  when: > 
    icloud_dir.stat.isdir is defined and icloud_dir.stat.isdir and 
    (icloud_path_dir.stat.isdir is not defined or not icloud_path_dir.stat.isdir) and 
    espanso_dir.stat.isdir is defined and espanso_dir.stat.isdir

# Both local and icloud environment exist. Move the existing configuration to .old.
- name: Move existing configuration
  ansible.builtin.include_tasks: move.yml
  when: >
    icloud_match_path_dir.stat.isdir is defined and icloud_match_path_dir.stat.isdir and 
    espanso_dir.stat.isdir is defined and espanso_dir.stat.isdir

# Create a symbolic link to icloud
- name: Create a symbolic link to icloud
  ansible.builtin.include_tasks: symlink.yml
