---
- name: Verify the config path
  ansible.builtin.stat:
    path: "{{ espanso_path }}/config"
  register: espanso_config_dir

- name: Verify the match path
  ansible.builtin.stat:
    path: "{{ espanso_path }}/match"
  register: espanso_match_dir

- name: Rename directories to .old
  command: 'mv "{{ espanso_path }}/{{ item }}" "{{ espanso_path }}/{{ item }}.old"'
  with_items:
    - config
    - match
  when: espanso_config_dir.stat.isdir is defined and espanso_config_dir.stat.isdir and espanso_match_dir.stat.isdir is defined and espanso_match_dir.stat.isdir

- name: Create a symbolic link to icloud
  ansible.builtin.file:
    src: "{{ icloud_path }}/{{ item }}"
    dest: "{{ espanso_path }}/{{ item }}"
    state: link
  with_items:
    - config
    - match
