---
# Make the cloud directory
- name: Ensure icloud path exists
  ansible.builtin.file:
    path: "{{ icloud_path }}"
    state: directory
    mode: 0750

- name: Create a symbolic link to icloud
  ansible.builtin.file:
    src: "{{ icloud_path }}"
    dest: "{{ espanso_path }}"
    state: link
