---
- name: Ensure icloud path exists
  ansible.builtin.file:
    path: "{{ espanso_path }}"
    state: directory
    mode: 0755

- name: Create a symbolic link to icloud
  ansible.builtin.file:
    src: "{{ icloud_path }}/{{ item }}"
    dest: "{{ espanso_path }}/{{ item }}"
    state: link
    force: true
  with_items:
    - config
    - match
